apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: infisical-static-secret
spec:
  infisicalAuthRef:
    name: {{ .Values.infisicalStaticSecret.infisicalAuthRef.name }}
    namespace: {{ .Values.infisicalStaticSecret.infisicalAuthRef.namespace }}

  syncOptions:
    refreshInterval: {{ .Values.infisicalStaticSecret.syncOptions.refreshInterval }}
    instantUpdates: {{ .Values.infisicalStaticSecret.syncOptions.instantUpdates }}

  sources:
    - projectId: {{ .Values.infisicalStaticSecret.sources.projectId }}
      environmentSlug: {{ .Values.infisicalStaticSecret.sources.environmentSlug }}
      secretPath: {{ .Values.infisicalStaticSecret.sources.secretPath }}

  targets:
    - name: {{ .Values.infisicalStaticSecret.targets.name }}
      namespace: {{ .Values.infisicalStaticSecret.targets.namespace }}
      kind: Secret
      creationPolicy: Owner
